// Code generated by daggen. DO NOT EDIT.
package op

import (
	"fmt"

	"github.com/akennis/dagor/examples/roughrank/model"
)

func (op *CalcSimOp) InputFields() map[string]any {
	return map[string]any{
		"userEmb": &op.userEmb, "streamEmbs": &op.streamEmbs,
	}
}

func (op *CalcSimOp) OutputFields() map[string]any {
	return map[string]any{
		"scores": &op.scores,
	}
}

func (op *CalcSimOp) SetInputField(field string, value any) error {
	switch field {
	case "userEmb":
		if val, ok := value.(*[]float64); ok {
			op.userEmb = val
		} else {
			return fmt.Errorf("field %s is not type of *[]float64", field)
		}
	case "streamEmbs":
		if val, ok := value.(*[]*model.StreamEmb); ok {
			op.streamEmbs = val
		} else {
			return fmt.Errorf("field %s is not type of *[]*model.StreamEmb", field)
		}

	default:
		return fmt.Errorf("field %s is not defined", field)
	}
	return nil
}

func (op *CalcSimOp) ResetFields() {
	var zerouserEmb *[]float64
	op.userEmb = zerouserEmb
	var zerostreamEmbs *[]*model.StreamEmb
	op.streamEmbs = zerostreamEmbs

	var zeroscores []*model.Score
	op.scores = zeroscores

}
