// Code generated by daggen. DO NOT EDIT.
package op

import (
	"fmt"
)

func (op *GetUserEmbOp) InputFields() map[string]any {
	return map[string]any {
		"userId": &op.userId,
	}
}

func (op *GetUserEmbOp) OutputFields() map[string]any {
	return map[string]any {
		"userEmb": &op.userEmb,
	}
}

func (op *GetUserEmbOp) SetInputField(field string, value any) error {
	switch field {
	case "userId":
		if val, ok := value.(*int64); ok {
			op.userId = val
		} else {
			return fmt.Errorf("field %s is not type of *int64", field)
		}
	
	default:
		return fmt.Errorf("field %s is not defined", field)
	}
	return nil
}

func (op *GetUserEmbOp) ResetFields() {
	var zerouserId *int64
	op.userId = zerouserId
	
	var zerouserEmb []float64
	op.userEmb = zerouserEmb
	
}