// Code generated by daggen. DO NOT EDIT.
package op

import (
	"fmt"

	"github.com/wwz16/dagor/examples/roughrank/model"
)

func (op *GetStreamEmbsOp) InputFields() map[string]any {
	return map[string]any{
		"streamIds": &op.streamIds,
	}
}

func (op *GetStreamEmbsOp) OutputFields() map[string]any {
	return map[string]any{
		"streamEmbs": &op.streamEmbs,
	}
}

func (op *GetStreamEmbsOp) SetInputField(field string, value any) error {
	switch field {
	case "streamIds":
		if val, ok := value.(*[]int64); ok {
			op.streamIds = val
		} else {
			return fmt.Errorf("field %s is not type of *[]int64", field)
		}

	default:
		return fmt.Errorf("field %s is not defined", field)
	}
	return nil
}

func (op *GetStreamEmbsOp) ResetFields() {
	var zerostreamIds *[]int64
	op.streamIds = zerostreamIds

	var zerostreamEmbs []*model.StreamEmb
	op.streamEmbs = zerostreamEmbs

}
