// Code generated by daggen. DO NOT EDIT.
package op

import (
	"fmt"
)

func (op *InitOp) InputFields() map[string]any {
	return map[string]any {
		
	}
}

func (op *InitOp) OutputFields() map[string]any {
	return map[string]any {
		"userId": &op.userId,"streamIds": &op.streamIds,
	}
}

func (op *InitOp) SetInputField(field string, value any) error {
	switch field {
	
	default:
		return fmt.Errorf("field %s is not defined", field)
	}
	return nil
}

func (op *InitOp) ResetFields() {
	
	var zerouserId int64
	op.userId = zerouserId
	var zerostreamIds []int64
	op.streamIds = zerostreamIds
	
}