// Code generated by daggen. DO NOT EDIT.
package op

import (
	"fmt"

	"github.com/akennis/dagor/examples/roughrank/model"
)

func (op *RespOp) InputFields() map[string]any {
	return map[string]any{
		"userId": &op.userId, "scores": &op.scores,
	}
}

func (op *RespOp) OutputFields() map[string]any {
	return map[string]any{
		"resp": &op.resp,
	}
}

func (op *RespOp) SetInputField(field string, value any) error {
	switch field {
	case "userId":
		if val, ok := value.(*int64); ok {
			op.userId = val
		} else {
			return fmt.Errorf("field %s is not type of *int64", field)
		}
	case "scores":
		if val, ok := value.(*[]*model.Score); ok {
			op.scores = val
		} else {
			return fmt.Errorf("field %s is not type of *[]*model.Score", field)
		}

	default:
		return fmt.Errorf("field %s is not defined", field)
	}
	return nil
}

func (op *RespOp) ResetFields() {
	var zerouserId *int64
	op.userId = zerouserId
	var zeroscores *[]*model.Score
	op.scores = zeroscores

	var zeroresp model.Response
	op.resp = zeroresp

}
