package main

import (
	"bytes"
	"flag"
	"fmt"
	"go/ast"
	"go/format"
	"go/parser"
	"go/token"
	"html/template"
	"log"
	"os"
	"strings"
)

// daggen is a tool to generate code for operators.
// example:
// go run cmd/daggen/main.go -type=AddOp
// go run cmd/daggen/main.go -type=AddOp -output=add_op_gen.go

var (
	typeFlag   = flag.String("type", "", "struct name; must be set")
	outputFlag = flag.String("output", "", "output file name")
)

const (
	fileTpl = `// Code generated by daggen. DO NOT EDIT.
package {{.PkgName}}

import (
	"fmt"
)

func (op *{{.OpName}}) InputFields() map[string]any {
	return map[string]any {
		{{range $i, $field := .Inputs}}"{{$field.Name}}": &op.{{$field.Name}},{{end}}
	}
}

func (op *{{.OpName}}) OutputFields() map[string]any {
	return map[string]any {
		{{range $i, $field := .Outputs}}"{{$field.Name}}": &op.{{$field.Name}},{{end}}
	}
}

func (op *{{.OpName}}) SetInputField(field string, value any) error {
	switch field {
	{{range $i, $field := .Inputs}}case "{{$field.Name}}":
		if val, ok := value.({{$field.Type}}); ok {
			op.{{$field.Name}} = val
		} else {
			return fmt.Errorf("field %s is not type of {{$field.Type}}", field)
		}
	{{end}}
	default:
		return fmt.Errorf("field %s is not defined", field)
	}
	return nil
}

func (op *{{.OpName}}) ResetFields() {
	{{range $i, $field := .Inputs}}var zero{{$field.Name}} {{$field.Type}}
	op.{{$field.Name}} = zero{{$field.Name}}
	{{end}}
	{{range $i, $field := .Outputs}}var zero{{$field.Name}} {{$field.Type}}
	op.{{$field.Name}} = zero{{$field.Name}}
	{{end}}
}`
)

type FieldInfo struct {
	Name string
	Type string
}

func main() {
	flag.Parse()
	opName := *typeFlag
	if opName == "" {
		fmt.Println("type name is required")
		os.Exit(1)
	}
	outName := *outputFlag
	if outName == "" {
		outName = strings.ToLower(opName) + "_gen.go"
	}

	// parse current pkg
	fset := token.NewFileSet()
	pkgs, err := parser.ParseDir(fset, ".", nil, parser.ParseComments)
	if err != nil {
		log.Fatalf("failed to parse current pkg: %v", err)
	}

	var pkgName string
	var targetStruct *ast.StructType

	// find the target struct
	for name, pkg := range pkgs {
		pkgName = name
		for _, file := range pkg.Files {
			ast.Inspect(file, func(n ast.Node) bool {
				ts, ok := n.(*ast.TypeSpec)
				if !ok || ts.Name.Name != opName {
					return true
				}
				st, ok := ts.Type.(*ast.StructType)
				if !ok {
					log.Fatalf("%s is not a struct", opName)
				}
				targetStruct = st
				return false
			})
		}
	}
	if targetStruct == nil {
		log.Fatalf("struct %s not found", opName)
	}

	// extract the input and output fields from the target struct
	inputs, outputs := getOpInputsOutputs(targetStruct)

	// render the code by template
	code := ""
	opCode := renderCode(pkgName, opName, inputs, outputs)
	code += opCode

	// write file
	if err := writeFile(outName, code); err != nil {
		log.Fatalf("failed to write file %s: %v", outName, err)
	}
	fmt.Printf("generated file: %s\n", outName)
}

func getOpInputsOutputs(targetStruct *ast.StructType) ([]*FieldInfo, []*FieldInfo) {
	inputs := make([]*FieldInfo, 0)
	outputs := make([]*FieldInfo, 0)

	for _, field := range targetStruct.Fields.List {
		if field.Tag == nil || len(field.Names) == 0 {
			continue
		}
		tag := field.Tag.Value
		fieldName := field.Names[0].Name
		fieldType := getFieldType(field.Type)

		if strings.Contains(tag, `dag:"input"`) {
			inputs = append(inputs, &FieldInfo{Name: fieldName, Type: fieldType})
		} else if strings.Contains(tag, `dag:"output"`) {
			outputs = append(outputs, &FieldInfo{Name: fieldName, Type: fieldType})
		}
	}
	return inputs, outputs
}

func getFieldType(expr ast.Expr) string {
	var buf bytes.Buffer
	// format.Node 可以将 ast 节点转换回符合语法的源代码字符串
	if err := format.Node(&buf, token.NewFileSet(), expr); err != nil {
		return ""
	}
	return buf.String()
}

func renderCode(pkgName, opName string, inputs, outputs []*FieldInfo) string {
	data := struct {
		PkgName string
		OpName  string
		Inputs  []*FieldInfo
		Outputs []*FieldInfo
	}{
		PkgName: pkgName,
		OpName:  opName,
		Inputs:  inputs,
		Outputs: outputs,
	}

	tmpl, err := template.New("fileTpl").Parse(fileTpl)
	if err != nil {
		log.Fatalf("failed to parse file template: %v", err)
	}

	var buf bytes.Buffer
	err = tmpl.Execute(&buf, data)
	if err != nil {
		log.Fatalf("failed to execute file template: %v", err)
	}
	return buf.String()
}

func writeFile(name, code string) error {
	f, err := os.Create(name)
	if err != nil {
		return fmt.Errorf("failed to create file %s: %w", name, err)
	}
	defer f.Close()

	_, err = f.WriteString(code)
	if err != nil {
		return fmt.Errorf("failed to write to file %s: %w", name, err)
	}
	return nil
}
