// Code generated by daggen. DO NOT EDIT.
package op

import (
	"fmt"
)

func (op *AddOp) InputFields() map[string]any {
	return map[string]any {
		"a": &op.a,"b": &op.b,
	}
}

func (op *AddOp) OutputFields() map[string]any {
	return map[string]any {
		"sum": &op.sum,
	}
}

func (op *AddOp) SetInputField(field string, value any) error {
	switch field {
	case "a":
		if val, ok := value.(*int); ok {
			op.a = val
		} else {
			return fmt.Errorf("field %s is not type of *int", field)
		}
	case "b":
		if val, ok := value.(*int); ok {
			op.b = val
		} else {
			return fmt.Errorf("field %s is not type of *int", field)
		}
	
	default:
		return fmt.Errorf("field %s is not defined", field)
	}
	return nil
}

func (op *AddOp) ResetFields() {
	var zeroa *int
	op.a = zeroa
	var zerob *int
	op.b = zerob
	
	var zerosum int
	op.sum = zerosum
	
}