// Code generated by daggen. DO NOT EDIT.
package op

import (
	"fmt"
)

func (op *ConstOp) InputFields() map[string]any {
	return map[string]any {
		
	}
}

func (op *ConstOp) OutputFields() map[string]any {
	return map[string]any {
		"out": &op.out,
	}
}

func (op *ConstOp) SetInputField(field string, value any) error {
	switch field {
	
	default:
		return fmt.Errorf("field %s is not defined", field)
	}
	return nil
}

func (op *ConstOp) ResetFields() {
	
	var zeroout int
	op.out = zeroout
	
}