// Code generated by daggen. DO NOT EDIT.
package op

import (
	"fmt"
)

func (op *LogOp) InputFields() map[string]any {
	return map[string]any {
		"x": &op.x,
	}
}

func (op *LogOp) OutputFields() map[string]any {
	return map[string]any {
		"result": &op.result,
	}
}

func (op *LogOp) SetInputField(field string, value any) error {
	switch field {
	case "x":
		if val, ok := value.(*int); ok {
			op.x = val
		} else {
			return fmt.Errorf("field %s is not type of *int", field)
		}
	
	default:
		return fmt.Errorf("field %s is not defined", field)
	}
	return nil
}

func (op *LogOp) ResetFields() {
	var zerox *int
	op.x = zerox
	
	var zeroresult float64
	op.result = zeroresult
	
}